# Oral History as Data (OHD) - a Lib-STATIC Tool
# https://github.com/uidaholib/oral-history-as-data


##########
# URL settings 
#
# url is your gh-pages base, following the pattern: username.github.io
url: https://vanlibrarijan.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /ohd
# repository is the github repository's full url
repository: https://github.com/vanlibrarijan/ohd


##########
# Site settings
#
# title of site appears in banner
title: Transcript Data
# tagline appears in banner
tagline: Transcriptions of focus groups for the UBC iSchool study Does what you study indicate your awareness of the effects of data-driven technologies? 
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Transcript Data / Does what you study indicate your awareness of the effects of data-driven technologies? "
# Organization branding
organization-name: UBC School of Information
organization-link: https://ischool.ubc.ca/
organization-logo-banner: https://ischool.ubc.ca/files/2015/06/logo.png
organization-logo-nav: https://ischool.ubc.ca/files/2015/06/logo.png


####### Leave the Below As Is ########

# Jekyll collections settings
collections:
  transcripts:
    output: true
    permalink: /:collection/:name
  howto:
    output: true
    permalink: /:collection/:name
# defaults
defaults:
  - scope:
      type: transcripts
    values:
      layout: transcript
  - scope:
      type: howto
    values:
      layout: howto

# Build settings
markdown: kramdown
